"use client";

import React from "react";
import { motion } from "framer-motion";

export function ManifestoSection() {
  return (
    <section id="manifesto" className="relative py-32 px-page bg-transparent text-foreground z-10 flex flex-col items-center">
      <div className="w-full max-w-[65ch] mx-auto">

        {/* The Human Note */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
          className="mb-16 p-6 border border-accent/30 bg-accent-muted/5 rounded-xl relative overflow-hidden group"
        >
          <div className="absolute top-0 left-0 w-1 h-full bg-accent"></div>
          <p className="font-mono text-xs uppercase tracking-widest text-accent mb-2 flex items-center gap-2">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z" />
            </svg>
            Editor's Note
          </p>
          <p className="font-['Cormorant_Garamond'] italic text-xl md:text-2xl text-foreground/90 leading-relaxed">
            This piece is not generated by AI. It was written entirely by me. Read with your heart, as I have written this with mine.
          </p>
        </motion.div>

        {/* The Content */}
        <div className="space-y-16 font-body font-light text-lg md:text-xl leading-[1.8] text-foreground/80">

          {/* Intro */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
          >
            <p className="first-letter:font-['Playfair_Display'] first-letter:text-7xl first-letter:font-bold first-letter:mr-3 first-letter:float-left first-letter:leading-[0.8] first-letter:text-foreground">
              Hi. I'm Raunak. BioTech student at NIT Durgapur — one of India's Institutes of National Importance. Which means I spend my mornings reading about protein folding and my nights writing TypeScript. Make of that what you will.
            </p>
            <p className="mt-6">
              I speak English, Hindi, and Nepali. Passable Bengali. Four languages means four ways of thinking about how meaning moves between people. That's not a fun fact — it's probably why I ended up caring so much about interfaces.
            </p>
          </motion.div>

          {/* On Design */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
          >
            <h3 className="font-display text-2xl font-semibold mb-4 text-foreground tracking-tight">On design:</h3>
            <p>
              The question I can't stop asking is: how does it feel to be inside this thing?
              Not "does it look good" — that's the easy question. The harder ones: where does the eye go first? What does the scroll do to your sense of time? What does the silence between two elements communicate?
            </p>
            <p className="mt-6">
              I built Akshar — a writing platform — in brutalist design. Not brutal as in harsh. Brutal as in honest. Raw material, exposed structure, nothing decorating itself into something it isn't. Heavy type, deliberate negative space, a cursor that changes behaviour depending on context. I used Framer Motion to make interactions feel physical rather than digital — like the page has actual weight. I wanted opening it to feel like sitting down at a serious desk. Like the act of launching it signals something to yourself.
            </p>
            <p className="mt-6">
              The Literary Circle's event platform runs bidirectional scroll-linked timelines, parallax physics, GPU-accelerated marquees — and still loads fast. I cut payload by 35% and First Contentful Paint by 1.2 seconds on a production site. I mention the numbers not to flex but because I think performance and beauty are the same problem seen from different angles. A site that's visually careful but slow is lying about who it is.
            </p>
          </motion.div>

          {/* On Backend */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
          >
            <h3 className="font-display text-2xl font-semibold mb-4 text-foreground tracking-tight">On the backend:</h3>
            <p>
              I build secure, clean systems — Node.js, PostgreSQL, Express, JWT pipelines, real-time infrastructure with Socket.io. I say this not to pad a list but because full-stack thinking genuinely changes how you approach the frontend. When you understand the data underneath, you stop designing for what you wish were true and start designing for what actually is.
            </p>
            <p className="mt-6">
              ContestHub has a real-time anti-cheat engine that monitors viewport context switches via the Visibility API, enforces a 10-second grace period, then triggers a server-side auto-submit. I built that because I noticed blur fires when you alt-tab to your terminal — but visibilitychange doesn't. In a competitive programming contest, a terminal is exactly where cheating lives. That's the kind of detail that matters.
            </p>
          </motion.div>

          {/* On Writing & SEO/GEO */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
          >
            <h3 className="font-display text-2xl font-semibold mb-4 text-foreground tracking-tight">On writing:</h3>
            <p>
              I used to write too — an independent blog, freelance pieces, commentary. I say this because it shapes how I think about design: both are translation work. You take something complex and make it legible without making it simple. That's the whole job, really, whether the medium is prose, type, or code.
              ALso I have pretty hands on experience with Graphic Designing; Adobe Photoshop and other design tools.
              For my college body, I have done Graphic designing for more than a year. It means I do have a design sense.
            </p>
            <p className="mt-6 border-l-2 border-foreground/20 pl-4 italic">
              This background in writing also evolved into deep technical experience with SEO (Search Engine Optimization) and GEO (Generative Engine Optimization). I understand how to structure content and metadata not just for human readers, but for the algorithms and LLMs (like ChatGPT) that now parse, index, and retrieve our digital information. The mechanics of visibility are just as important as the content itself.
            </p>
          </motion.div>

          {/* What I'm building next */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
          >
            <h3 className="font-display text-2xl font-semibold mb-4 text-foreground tracking-tight">What I'm building next:</h3>
            <p className="text-sm uppercase tracking-widest font-mono text-foreground/50 mb-8">(Still learning. Still figuring these out. But I think they're worth figuring out.)</p>

            <div className="space-y-10">
              <div>
                <h4 className="font-bold text-foreground font-display text-xl mb-2">Genomic Report UI / AI-Assisted Interpretation Layer</h4>
                <p>
                  Raw DNA sequencing outputs are notoriously unreadable — walls of variant codes, rsIDs, and confidence intervals that even clinicians struggle to parse fast. I'm exploring building an interface layer that takes VCF files (Variant Call Format — the standard genomic output), runs them against public databases (ClinVar, gnomAD) via API, and surfaces a clean, readable risk summary with an LLM interpretation layer on top. Stack: Next.js, Python FastAPI, Google Gemini API, PostgreSQL. The design problem is the interesting part: how do you communicate probability and uncertainty to someone who is scared?
                </p>
              </div>

              <div>
                <h4 className="font-bold text-foreground font-display text-xl mb-2">Drug-Target Interaction Predictor — Browser-Native</h4>
                <p>
                  Most ML tools for molecular biology still live in Jupyter notebooks that only bioinformaticians can run. I want to build a web interface where a researcher pastes a SMILES string (a text encoding of a molecule's structure) and gets a predicted binding affinity score against a protein target — using a fine-tuned GNN (Graph Neural Network) served via a FastAPI endpoint. Frontend in Next.js, model in PyTorch, inference via Python backend. Still learning the GNN side. But the gap between "model exists in research paper" and "anyone can use it in a browser" is where I want to work.
                </p>
              </div>

              <div>
                <h4 className="font-bold text-foreground font-display text-xl mb-2">Clinical Trial Matching Engine</h4>
                <p>
                  There are thousands of open clinical trials at any moment. Patients and doctors rarely find the right ones because the matching is done manually against dense eligibility criteria text. I'm building a semantic search layer using embeddings (likely via Google's text-embedding API) over ClinicalTrials.gov data — a clean Next.js interface where you input symptoms, conditions, and location, and get ranked trial matches with plain-language eligibility summaries. Not a chatbot. A real search tool with a real index. Stack: Next.js, FastAPI, PostgreSQL with pgvector, Google Generative AI.
                </p>
              </div>
            </div>

            <p className="mt-12 font-medium text-foreground">
              These aren't lab projects. They're software problems that happen to live at the edge of biology. I'm a developer first — I just have the unusual advantage of understanding both sides of that edge.
            </p>
          </motion.div>

        </div>
      </div>
    </section>
  );
}
